# Generated by Django 2.2 on 2022-07-18 11:16

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_pan',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=accounts.models.upload_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_reg_certificate',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=accounts.models.upload_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='other_uploads',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=accounts.models.upload_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg'])]),
        ),
    ]
