# Generated by Django 2.2 on 2022-07-19 05:23

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220718_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='identification',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=accounts.models.inv_upld_pth, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg'])]),
        ),
    ]
