# Generated by Django 2.2 on 2022-07-18 10:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_requested', models.BooleanField(default=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('request_date', models.TimeField(default=django.utils.timezone.now)),
                ('accept_date', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=125)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SavedFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Feed')),
            ],
        ),
        migrations.CreateModel(
            name='SavedBlogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyToFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('reply', models.CharField(max_length=125)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Feed')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyToBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('reply', models.CharField(max_length=125)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Blog')),
            ],
        ),
    ]
