# Generated by Django 2.2 on 2022-07-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('employee_type', models.CharField(max_length=55)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255, null=True)),
                ('is_currently_working', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Seeker')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=80)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Seeker')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_ongoing', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('project_url', models.URLField()),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Seeker')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseAndCerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuing_organisation', models.CharField(max_length=255)),
                ('is_credential_nonexpiry', models.BooleanField(default=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(max_length=255)),
                ('credential_url', models.URLField(max_length=255)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Seeker')),
            ],
        ),
        migrations.CreateModel(
            name='HonorsAndAwards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Seeker')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=40)),
                ('grade_type', models.CharField(default='Percentage', max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Seeker')),
            ],
        ),
    ]
